spring:
  cloud:
    gateway:
      routes:
        - id: railway-user-service
          uri: lb://railway-user${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/logout